name: vdo_ninja
description: Simple capture app for VDO.NInja
version: 5.0.23+23
versionCode: 23

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.9.41
  shared_preferences: ^2.0.8
  http: ^1.1.0
  path_provider: ^2.0.2
  wakelock: ^0.6.1+1
  js: ^0.6.3
  share: ^2.0.4
  webview_flutter: ^4.2.2
  url_launcher: ^6.0.12
  permission_handler: ^10.4.3
  encrypt: ^5.0.1
  tuple: ^2.0.2
  flutter_background:
    git:
      url: https://github.com/JulianAssmann/flutter_background
      ref: master    

dev_dependencies:
  flutter_test:
    sdk: flutter

    

flutter:
  uses-material-design: true
