name: vdo_ninja
description: Simple capture app for VDO.Ninja
version: 5.0.38+38
versionCode: 38

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.12.1+hotfix.1
  shared_preferences: ^2.0.8
  http: ^1.1.0
  path_provider: ^2.0.2
  wakelock:
    git:
      url: https://github.com/steveseguin/wakelock
      ref: main
      path: wakelock
  
  js: ^0.7.1
  share: ^2.0.4
  webview_flutter: ^4.2.2
  url_launcher: ^6.0.12
  permission_handler: ^11.1.0
  encrypt: ^5.0.1
  tuple: ^2.0.2
  device_info_plus: ^11.0.0
  flutter_background:
    git:
      url: https://github.com/steveseguin/flutter_background/
      ref: master   

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  win32: ^5.5.4

flutter:
  uses-material-design: true
